linters-settings:
  varnamelen:
    min-name-length: 1
linters:
  enable-all: true
  disable:
    - bodyclose
    - contextcheck
    - dupl
    - exhaustivestruct
    - exhaustruct
    - gci
    - gochecknoinits
    - gochecknoglobals
    - golint
    - gomoddirectives
    - interfacer
    - ireturn
    - maligned
    - nilerr
    - noctx
    - rowserrcheck
    - scopelint
    - structcheck
    - sqlclosecheck
    - tagliatelle
    - tparallel
    - unparam
    - wastedassign
    - wrapcheck
issues:
  exclude-rules:
    - path: _test\.go
      linters: 
        - funlen
